#!/bin/bash
#grab the location of hashcat.restore
location="$(find hashcat.restore / 2> /dev/null | grep hashcat.restore)" && echo "hashcat.restore found in $location, copying now :3"
#grabs the name of the file that the restore file is using
hashfilename="$(tail -n 1 $location)"
cp $location ~/Downloads/$hashfilename.restoreHC 2> /dev/null || echo "failed. This doesnt actually happen unless you dont have a download folder in your home folder. Maybe youre running as root for some reason?"
