#!/bin/bash
#grabs the name of the file its restoring, which is stored in the third line
location="$(find john.rec / 2> /dev/null | grep john.rec)" && echo "john.rec found in $location, copying now :3"
hashfilename="$(head -n 3 $location | tail -n 1 | xargs)"
#copies it somewhere, adding the name of the hash file to the front of it. replace '/mnt/c/Users...' to the directory youd like it to copy to, and add $hashfilename\.john.rec to the end of it. also replace FemBit with your username. 
cp $location ~/Downloads/$hashfilename.john.rec
#if youd like to run this as a crontab for every minute, do crontab -e and paste this: * * * * * /path/to/downloaded/script
